[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_RUNTIME_CONFIG_ENABLED = "true"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'self' https://qkimxruewcensbnfllvv.supabase.co https://unpkg.com 'unsafe-inline' 'unsafe-eval'; img-src 'self' data:; style-src 'self' https://cdn.jsdelivr.net 'unsafe-inline';"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    X-Content-Type-Options = "nosniff"
